- hosts: all
  tasks:
          - name: folder create
            file:
                    path: /dvd
                    state: directory
          - name: folder mount
            mount:
                    path: /dvd
                    src: /dev/sr0
                    fstype: iso9660
                    state: mounted
                    
          - name: create local repo
            copy:
                    src: ./local.repo
                    dest: /etc/yum.repos.d/

